<!DOCTYPE html>
<html lang="en">
    <head>
	    <meta charset="utf-8" />
	    <title>Menu</title>
	    <link href="css/styles.css" rel="stylesheet" />
        <link rel="icon" type="image/pizzaicon" href="images/pizzaicon.png">
    </head>
    <body>
        <header>
            <?php
				//Grab Site Navigation
				include('nav.php')
			?>
        </header>
        <main>
            <!--div which contains the three big pizza crust displays
            all images were generated by grok.com-->
           <div class="pizzaoptions">
                <div class="pizzaheadings"><a href="pizzabuild.php?type=Original"><h1>ORIGINAL CRUST</h1><img src="images/original2.jpg"></a><p>Our <em>FAMOUS</em> original crust, soft, fluffy, and cooked to perfection.</p></div>
                <div class="pizzaheadings"><a href="pizzabuild.php?type=Deepdish"><h1>DEEP DISH</h1><img src="images/deepdish.jpg"></a><p>Our delightfully deep dished Chicago style crust. For the deep soul and deeper stomach.</p></div>
                <div class="pizzaheadings"><a href="pizzabuild.php?type=Thincrust"><h1>THIN CRUST</h1><img src="images/thincrust.jpg"></a><p>Our thin bread, classic style crust. Just like mama used to make.</p></div>
           </div>
           <div class="menutoppings"><!--div which contains the available toppings, and images for each-->
                <h2>AVAILABLE TOPPINGS</h2>
                <div class="toppingoptions">
                    <ul>
<!--Image references
cheddar https://www.agropursolutions.ca/en/products/cheese/coloured-cheddar/25kg-shredded-medium-coloured-cheddar-34-mf
mozzarella https://avron.ca/en/shredded-mozzarella-cheese.html
Vegan https://thebehive.com/products/garlic-chz-shredz-6-pack
Tomato sauce https://pngtree.com/freepng/thick-and-rich-tomato-ketchup_18972477.html
Marinara sauce https://www.vecteezy.com/png/48113524-marinara-sauce-in-a-white-bowl-transparent-background
Alfredo sauce https://www.vecteezy.com/png/48113524-marinara-sauce-in-a-white-bowl-transparent-background
Peppers https://adamsapplellc.com/product/cut-bell-pepper-green/
Tomatoes https://gofreshusa.com/product/gofresh/vegetables/tomatoes/tomato-sliced-2-5-lb/
Olives https://www.pcfreshco.com/sliced-black-olives-no10can-oliblan10sli/
Onions https://gofreshusa.com/product/gofresh/vegetables/onions/onion-red-sliced-tray-pk-4-5-lb/
Pepperoni https://www.gfsstore.com/en-us/products/429267/
Bacon https://www.foodnetwork.com/recipes/food-network-kitchen/real-bacon-bits-recipe-2106075
Chicken https://www.aubut.ca/en/products/details/frozen-fully-cooked-grilled-chicken-breast-strips-15641
Ham https://kerrigans.ie/products/diced-ham
-->
                        <li><h3>CHEESE</h3></li>
                        
                        <li>Cheddar<img src="images/Cheddar.JPG" alt="shredded cheddar jpeg" href="https://www.agropursolutions.ca/en/products/cheese/coloured-cheddar/25kg-shredded-medium-coloured-cheddar-34-mf"</li>
                        
                        <li>Mozzarella<img src="images/Mozzarella.webp" alt="shredded mozzarella webp" href="mozzarella https://avron.ca/en/shredded-mozzarella-cheese.html"</li>
                        
                        <li>Vegan<img src="images/Vegan.webp" alt="shredded vegan cheese webp" href="https://thebehive.com/products/garlic-chz-shredz-6-pack"</li>
                    </ul>
                    <ul>
                        <li><h3>SAUCE</h3></li>
                        
                        <li>Tomato<img src="images/Tomatosauce.png" alt="tomato sauce png" href="https://pngtree.com/freepng/thick-and-rich-tomato-ketchup_18972477.html"</li>
                        
                        <li>Marinara<img src="images/Marinara.png" alt="marinara sauce png" href="https://www.vecteezy.com/png/48113524-marinara-sauce-in-a-white-bowl-transparent-background"</li>
                        
                        <li>Alfredo<img src="images/Alfredo.webp" alt="alfredo sauce webp" href="https://www.vecteezy.com/png/48113524-marinara-sauce-in-a-white-bowl-transparent-background"</li>
                    </ul>
                    <ul>
                        <li><h3>MEATS</h3></li>
                        
                        <li>Pepperoni<img src="images/Pepperoni.jpg" alt="pepperoni png" href="https://www.gfsstore.com/en-us/products/429267/"</li>
                        
                        <li>Bacon<img src="images/Bacon.webp" alt="bacon webp" href="https://www.foodnetwork.com/recipes/food-network-kitchen/real-bacon-bits-recipe-2106075"</li>
                        
                        <li>Chicken<img src="images/Chicken.webp" alt="chicken webp" href="https://www.aubut.ca/en/products/details/frozen-fully-cooked-grilled-chicken-breast-strips-15641"</li>
                        
                        <li>Ham<img src="images/dicedham.webp" class="hamimg" alt="diced ham webp" href="https://kerrigans.ie/products/diced-ham"</li>
                    </ul>
                    <ul>
                        <li><h3>VEGGIES</h3></li>
                        
                        <li>Peppers<img src="images/Greenpepper.png" alt="green peppers png" href="https://adamsapplellc.com/product/cut-bell-pepper-green/"</li>
                        
                        <li>Onions<img src="images/red-onion-sliced.webp" alt="red onion webp" href="https://gofreshusa.com/product/gofresh/vegetables/onions/onion-red-sliced-tray-pk-4-5-lb/"</li>
                        
                        <li>Tomatoes<img src="images/tomato-sliced.webp" alt="sliced tomatoes webp" href="https://gofreshusa.com/product/gofresh/vegetables/tomatoes/tomato-sliced-2-5-lb/"</li>
                        
                        <li>Olives<img src="images/Olives.jpg" alt="sliced olives jpeg" href="https://www.pcfreshco.com/sliced-black-olives-no10can-oliblan10sli/"</li>
                    </ul>
                </div>
           </div>
        </main>
        <footer>
            <?php
				//Grab footer
				include('footer.php')
			?>
        </footer>
    </body>
</html>